### PR TITLE
remove typenum, use const-generics

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by mciantyre** [comment]
I've wanted this, but I've had trouble getting min const generics to express constraints with peripheral instances across crate boundaries. I pushed a commit to demonstrate what we can do today. Is there a way we can express something similar with min const generics?

**Comment by burrbull** [comment]
> I've wanted this, but I've had trouble getting min const generics to express constraints with peripheral instances across crate boundaries. I pushed a commit to demonstrate what we can do today using `typenum`. Is there a way we can express something similar with min const generics?

You try to compare `U<2>` with `typenum::U2`. Of course, these types are different.

**Comment by mciantyre** [comment]
I understand why the test fails. I want to learn what we would need to change in other imxrt-rs crates to support this PR.

Does `struct U<const N: u8>` and its accompanying traits and alias belong in a separate crate? If the same types and traits were shared between `imxrt-iomuxc` and `imxrt-ral`, then the check proposed in the test would pass. Is that thinking correct?

**Comment by burrbull** [comment]
> If the same types and traits were shared between `imxrt-iomuxc` and `imxrt-ral`, then the check proposed in the test would pass. Is that thinking correct?

Yes, if you import these types instead of `typenum`'s check should be pass. These PR is done to be as minimal breaking as possible.
But you can go deeper and use const-generics directly as in https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/gpio.rs for example.

**Pull request merged**
