### PR TITLE
Add FlexIO definitions and 1060 pad config

### PR DESCRIPTION
**Pull request by Finomnis**

### CODE REVIEW

**Comment by Florob** [comment]
I had started on something similar for 1020, but put it on hold due to https://github.com/imxrt-rs/imxrt-ral/issues/32.
Have you already written a consumer for the `flexio::Pin` trait? My hunch is that having `const OFFSET: u32` rather than `type Pin: consts::Unsigned` is easier to work with. It also has precedence in `gpio::Pin`.

**Comment by Finomnis** [comment]
@Florob I didn't get to writing a consumer yet, but in theory I agree, so I changed it.

Is this what you had in mind?

**Comment by Florob** [comment]
> Is this what you had in mind?

Actually not. I was talking about the `Pin` associated type, not the generic.
I'd try to align with the `gpio::Pin` trait here, which has the generic as `consts::Unsigned`, and then an `OFFSET: u32` associated constant.

**Comment by Finomnis** [comment]
> Actually not. I was talking about the `Pin` associated type, not the generic. I'd try to align with the `gpio::Pin` trait here, which has the generic as `consts::Unsigned`, and then an `OFFSET: u32` associated constant.

I'm uncertain what you mean. `imxrt_iomux::gpio::Pin` has a `const N: u8` generic.

I adjusted it a little, is it better now?

**Comment by Finomnis** [comment]
@Florob I'm not far yet, so far I only print the parameters, but this is the driver I'm working on: https://github.com/Finomnis/ws2812-flexio
Just for information.

**Comment by Florob** [comment]
> I'm uncertain what you mean. imxrt_iomux::gpio::Pin has a const N: u8 generic.

I'm so sorry. I must somehow have been looking at an ancient revision. What you have now is indeed what I would have suggested.

> I'm not far yet, so far I only print the parameters, but this is the driver I'm working on: https://github.com/Finomnis/ws2812-flexio

That link 404s for me. Is the repository set to private perhaps?

**Comment by Finomnis** [comment]
@Florob Oops. Fixed. Apologies.

**Review by mciantyre — APPROVED** [review]
Thanks for reviewing the interface. I'll release in v0.2.

**Pull request merged**
